# Action 的名字
name: blog auto Developed

on:
  # 触发条件1：main 分支收到 push 后执行任务。
  push:
    branches:
      - main
  # 触发条件2：手动按钮
  workflow_dispatch:

# 这里放环境变量,需要替换成你自己的
env:
  # Hexo 编译后使用此 git 用户部署到 github 仓库
  GIT_USER: feizhufanfan
  # Hexo 编译后使用此 git 邮箱部署到 github 仓库
  GIT_EMAIL: 1009963012@qq.com
  # Hexo 编译后要部署的 github 仓库
  # GIT_DEPLOY_REPO: feizhufanfan/feizhufanfan.github.io
  # # Hexo 编译后要部署到的分支
  # GIT_DEPLOY_BRANCH: main
  
  # # Hexo 编译后使用此 gitee 用户部署到gitee仓库
  # GITEE_USER: wbsu2003
  # # Hexo 编译后要部署的 gitee 仓库
  # GITEE_DEPLOY_REPO: wbsu2003/wbsu2003
  # # Hexo 编译后要部署到的分支
  # GITEE_DEPLOY_BRANCH: master
  
  # # 注意替换为你的 GitHub 源仓库地址
  # GIT_SOURCE_REPO: git@github.com:feizhufanfan/feizhufanfan.github.io.git
  # # 注意替换为你的 Gitee 目标仓库地址
  # GITEE_DESTINATION_REPO: git@gitee.com:wbsu2003/wbsu2003.git

jobs:
    build:
      name: Build on node ${{ matrix.node_version }} and ${{ matrix.os }}
      runs-on: ubuntu-latest
      if: github.event.repository.owner.id == github.event.sender.id
      strategy:
        matrix:
          os: [ubuntu-18.04]
          node_version: [16.14.0]

      steps:
        - name: Checkout Blog Src
          uses: actions/checkout@v2


        # - name: Checkout deploy repo
        #   uses: actions/checkout@v2
        #   with:
        #     repository: ${{ env.GIT_DEPLOY_REPO }}
        #     ref: ${{ env.GIT_DEPLOY_BRANCH }}
          

        - name: Use Node.js ${{ matrix.node_version }}
          uses: actions/setup-node@v2
          with:
            node-version: ${{ matrix.node_version }}
        


        - name: Configuration environment
          env:
            BLOG_HEXO_PRIVATE_KEY: ${{secrets.BLOG_HEXO_PRIVATE_KEY}}
          run: |
            echo "Configuration environment 当前运行的目录 $(pwd)"
            sudo timedatectl set-timezone "Asia/Shanghai"
          
            git config --global user.name ${{ env.GIT_USER}}
            git config --global user.email ${{ env.GIT_EMAIL }}
        
        - name: Install dependencies
          env:
            BLOG_HEXO_PRIVATE_KEY: ${{secrets.BLOG_HEXO_PRIVATE_KEY}}
          run: |
            echo "Configuration environment 当前运行的目录 $(pwd)"
            mkdir -p ~/.ssh/
            echo "$BLOG_HEXO_PRIVATE_KEY" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            eval $(ssh-agent)
            ssh-add ~/.ssh/id_rsa  
            npm install hexo-cli  -g
            npm install
            npm install hexo-deployer-git
            hexo
            hexo clean
    
        - name: Deploy Blog
          env:
            BLOG_HEXO_PRIVATE_KEY: ${{secrets.BLOG_HEXO_PRIVATE_KEY}}
          run: |
            mkdir -p ~/.ssh/
            sudo echo "$BLOG_HEXO_PRIVATE_KEY" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            eval $(ssh-agent)
            ssh-add ~/.ssh/id_rsa
            ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
            hexo generate
            echo "feizhufanfan.top" > public/CNAME
            cp README.md public/
            hexo deploy
            
        
        # # 以下为发布到gitee
        # - name: Sync to Gitee
        #   uses: wearerequired/git-mirror-action@master
        #   env:
        #     # 直接使用了 HEXO_DEPLOY_PRI
        #     SSH_PRIVATE_KEY: ${{ secrets.HEXO_DEPLOY_PRI }}
        #   with:
        #     # GitHub 源仓库地址
        #     source-repo: ${{ env.GIT_SOURCE_REPO }}
        #     # Gitee 目标仓库地址
        #     destination-repo: ${{ env.GITEE_DESTINATION_REPO }}

        # - name: Build Gitee Pages
        #   uses: yanglbme/gitee-pages-action@main
        #   with:
        #     # 你的 Gitee 用户名
        #     gitee-username: ${{ env.GITEE_USER }}
        #     # 注意在 Settings->Secrets 配置 GITEE_PASSWORD
        #     gitee-password: ${{ secrets.GITEE_PASSWORD }}
        #     # 你的 Gitee 仓库，仓库名严格区分大小写，请准确填写，否则会出错
        #     gitee-repo: ${{ env.GITEE_DEPLOY_REPO }}
        #     # 要部署的分支，默认是 master，若是其他分支，则需要指定（指定的分支必须存在）
        #     branch: ${{ env.GITEE_DEPLOY_BRANCH }}
  # ————————————————
  # 版权声明：本文为CSDN博主「杨浦老苏」的原创文章，遵循CC 4.0 BY-SA版权协议，转载请附上原文出处链接及本声明。
  # 原文链接：https://blog.csdn.net/wbsu2004/article/details/122661116

  # job2:
  #   build:
  #     name: 
